apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Jaeger
    type: jaeger
    url: http://localhost:16686
    access: proxy
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: "loki"
      httpMethod: GET
      nodeGraph:
        enabled: true
      spanBar:
        showProcess: true
