services:
  db_users:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/users:/var/lib/postgresql/data
    networks:
      - app-network

  db_sessions:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/sessions:/var/lib/postgresql/data
    networks:
      - app-network

  cache_users:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/users:/var/opt
    networks:
      - app-network

  cache_sessions:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis/sessions:/var/opt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
