[project]
name = "roberto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.10.5",
    "sqlalchemy>=2.0.37",
    "uvicorn>=0.34.0",
]
